name: neo_protocol
description: High-performance Flutter bindings for Neo Messaging Kernel
version: 0.1.0
homepage: https://github.com/neo-qiss/messaging-kernel

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  dio: ^5.3.2
  
  # Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Async and streams
  rxdart: ^0.27.7
  
  # Logging
  logger: ^2.0.2
  
  # Crypto
  crypto: ^3.0.3
  
  # Platform detection
  platform: ^3.1.0
  
  # Path
  path: ^1.8.3
  
  # Collection
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.2
  test: ^1.24.6

flutter:
  uses-material-design: true

# Code generation configuration
build_runner:
  builders:
    json_serializable:
      options:
        explicit_to_json: true
    freezed:
      options:
        fallbackUnion: true